- hosts: all
  become: yes
  tasks:
    - name: Install package on Debian systems
      apt:
        name: "{{ package }}"
        state: present
      when: ansible_os_family == "Debian"

    - name: Install package on RedHat systems
      yum:
        name: "{{ package }}"
        state: present
      when: ansible_os_family == "RedHat"
